### ISSUE TITLE
Bookcover won't display in Reading UI

### ISSUE THREAD

**Issue by bbuyukcelen** [RebusFoundation/reader-frontend#78]
Despite showing the book cover on the library, book cover won't display on the reading interface.
Screenshot attached, sending the epub via slack, with issue # attached. Tested on: Chrome Version 75.0.3770.100
![Screen Shot 2019-06-27 at 10 40 44 AM](https://user-images.githubusercontent.com/42753145/60277116-f1db2f00-98ca-11e9-9923-4fbf5694e262.png)

**Comment by baldurbjarnason** [comment]
Ah, I see why that happened. That epub is using an inline SVG to embed the cover (some books do this mostly, IIRC, because this allowed for better image scaling and centering on older Adobe RMSDK-based ebook readers) and Ink isn't updating the SVG <image> tag with the correct URL for the embedded image.

The good news is that this means the chapter XHTML is correctly being processed as XML and fixing should be a relatively simple matter.
